import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const sandbox = { window: { FrozenApp: {} }, URL };
for (const name of ['category-catalog', 'price-store', 'source-store']) vm.runInNewContext(fs.readFileSync(new URL('../assets/js/' + name + '.js', import.meta.url), 'utf8'), sandbox);
const app = sandbox.window.FrozenApp;
const store = app.sourceData.createStore();
assert.equal(app.sourceData.categories, app.priceData.categories);
assert.equal(store.sources.length, 9);
assert.equal(store.items.length, 21);
assert.equal(store.querySources({ status: 'pending' }).length, 2);
assert.equal(store.queryItems({ abnormal: 'yes' }).length, 6);
assert.equal(store.queryItems({ sourceId: 'src-1', status: 'pending', category: 'seafood' }).length, 1);
assert.equal(store.queryItems({ keyword: 'NO SUCH SOURCE' }).length, 0);
const base = { name: '新增虚构来源', type: 'industry', categories: ['poultry'], scope: '行业信息样例', url: 'https://new.example.com' };
const before = JSON.stringify(store.sources);
for (const patch of [{ name: '' }, { type: 'unknown' }, { categories: [] }, { categories: ['unknown'] }, { scope: '' }, { scope: '字'.repeat(201) }, { url: 'javascript:alert(1)' }, { url: 'https://name:password@example.com/' }, { url: 'bad url' }, { url: 'https://source-1.example.com#anchor' }, { name: '冷链政策与标准信息库' }]) {
  assert.equal(store.save({ ...base, ...patch }).valid, false);
}
assert.equal(JSON.stringify(store.sources), before);
const added = store.save(base);
assert.equal(added.valid, true);
assert.equal(added.source.status, 'pending');
assert.equal(added.source.url, 'https://new.example.com/');
assert.equal(store.save(base).valid, false);
assert.equal(store.queryItems({ sourceId: added.source.id }).length, 0);
assert.equal(store.save(base, added.source.id, 1).unchanged, true);
assert.equal(store.confirm(added.source.id, 1, ' ').valid, false);
assert.equal(store.confirm(added.source.id, 1, '已核对来源范围').valid, true);
assert.equal(store.confirm(added.source.id, 1, '重复确认').valid, false);

const item = store.findItem('info-1');
const source = store.find(item.sourceId);
assert.equal(store.eligible(item), true);
const originalContent = item.content;
const originalSnapshot = JSON.stringify(item.sourceSnapshot);
const oldItemLog = JSON.stringify(item.history[0]);
const saved = store.save({ ...source, scope: '调整后的演示信息范围' }, source.id, source.version);
assert.equal(saved.valid, true);
assert.equal(source.status, 'pending');
assert.equal(item.status, 'pending');
assert.equal(store.eligible(item), false);
assert.equal(item.content, originalContent);
assert.equal(JSON.stringify(item.sourceSnapshot), originalSnapshot);
assert.equal(JSON.stringify(item.history[0]), oldItemLog);
assert.equal(store.verify(item.id, item.version, 'verified', '已核对信息').valid, false);
assert.equal(store.confirm(source.id, source.version, '确认变更后的来源范围').valid, true);
assert.equal(item.status, 'pending');
assert.equal(store.verify(item.id, item.version, 'verified', '').valid, false);
assert.equal(store.verify(item.id, item.version, 'verified', '核对期间和来源原文').valid, true);
assert.equal(store.eligible(item), true);
assert.equal(item.verifiedSourceVersion, source.version);
assert.equal(store.verify(item.id, item.version, 'rejected', '重复核验').valid, false);
assert.equal(store.flag(item.id, item.version, '').valid, false);
assert.equal(store.flag(item.id, item.version, '发现发布时间不一致').valid, true);
assert.equal(store.eligible(item), false);
assert.equal(item.status, 'pending');
assert.equal(store.verify(item.id, item.version, 'rejected', '无法确认发布时间').valid, true);
assert.equal(store.eligible(item), false);
const rejectedSnapshot = JSON.stringify(item.history[item.history.length - 1]);
assert.equal(store.flag(item.id, item.version, '重新补充核验依据').valid, true);
assert.equal(store.verify(item.id, item.version - 1, 'verified', '过期提交').valid, false);
assert.equal(store.verify(item.id, item.version, 'verified', '已补充依据并核对').valid, true);
assert.equal(JSON.stringify(item.history[item.history.length - 3]), rejectedSnapshot);

// 缩小来源范围后，历史信息不能越过当前品类范围被标为可引用。
assert.equal(store.save({ ...source, categories: ['seafood'] }, source.id, source.version).valid, true);
assert.equal(store.confirm(source.id, source.version, '确认水产范围').valid, true);
assert.equal(store.verify(item.id, item.version, 'verified', '品类不在范围内').valid, false);
assert.equal(store.eligible(item), false);
assert.equal(store.verify(item.id, item.version, 'rejected', '品类超出来源范围').valid, true);
const unconfirmedItem = store.findItem('info-9');
assert.equal(store.verify(unconfirmedItem.id, unconfirmedItem.version, 'rejected', '来源尚未确认').valid, true);
assert.equal(store.save({ ...source, scope: '过期变更' }, source.id, source.version - 1).valid, false);
assert.equal(new Set(store.sources.map(source => source.id)).size, store.sources.length);
console.log('PASS: source validation, duplicate rejection, source/item state separation, scope checks, anomaly recheck, stale versions and original evidence retention. Node data checks only; no browser verification.');
